version: '3.1'

services:

  # Nipsr

  relay:
    build:
      context: ../relay
      dockerfile: ../relay/src/main/docker/Dockerfile.jvm
    restart: unless-stopped
    env_file:
      - env/db.env
      - env/relay.env
      - env/apps.rabbitmq.env
    depends_on:
      - rabbitmq
      - mongo

  processor:
    build:
      context: ../processor
      dockerfile: ../processor/src/main/docker/Dockerfile.jvm
    restart: unless-stopped
    env_file:
      - env/db.env
      - env/processor.env
      - env/apps.rabbitmq.env
    depends_on:
      - rabbitmq
      - mongo

  # Other

  nginx:
    image: nginx:1.23.3-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  rabbitmq:
    image: rabbitmq:3.10-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - env/rabbitmq.env

  mongo:
    image: mongo:6.0.4
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - env/db.env