quarkus:
  http:
    port: ${SERVER_PORT:8888}
    cors:
      ~: true
      origins: /.*/
      methods: GET,OPTIONS
      headers: accept,content-type
      exposed-headers: accept,content-type
      access-control-max-age: 24H
      access-control-allow-credentials: false
  mongodb:
    database: ${MONGODB_DATABASE:nipsr}
    connection-string: ${MONGODB_CONNECTION_STRING:mongodb://nipsr:nipsr@localhost:27017}
  rest-client:
    lnbits:
      url: ${LNBITS_API_URL:https://legend.lnbits.com/api/v1}

nipsr:
  management:
    nip05:
      min-digits: 2
      base-price: 100
    payment:
      lnbits:
        enabled: true
        api-key: ${LNBITS_API_KEY}