version: '3.1'

services:

  relay:
    image: com.nipsr/relay:latest-jvm
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - env/db.env
      - env/relay.env
      - env/apps.rabbitmq.env
    depends_on:
      - rabbitmq

  processor:
    image: com.nipsr/processor:latest-jvm
    restart: always
    ports:
      - "8088:8088"
    env_file:
      - env/db.env
      - env/processor.env
      - env/apps.rabbitmq.env
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.10-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - env/rabbitmq.env