quarkus:
  http:
    port: ${SERVER_PORT:8088}
  mongodb:
    database: ${MONGODB_DATABASE:nipsr}
    connection-string: ${MONGODB_CONNECTION_STRING:mongodb://nipsr:nipsr@localhost:27017}

mp:
  messaging:
    incoming:
      events:
        connector: smallrye-rabbitmq
        queue:
          name: received-events

rabbitmq-host: ${RABBITMQ_HOST:localhost}
rabbitmq-port: ${RABBITMQ_PORT:5672}
rabbitmq-username: ${RABBITMQ_USER:nipsr}
rabbitmq-password: ${RABBITMQ_PASS:nipsr}