version: '3.1'

services:

  # Nipsr

  relay:
    image: ghcr.io/gmrms/nipsr/relay:latest
    restart: always
    env_file:
      - env/db.env
      - env/relay.env
      - env/apps.rabbitmq.env
    depends_on:
      - rabbitmq

  processor:
    image: ghcr.io/gmrms/nipsr/processor:latest
    restart: always
    env_file:
      - env/db.env
      - env/processor.env
      - env/apps.rabbitmq.env
    depends_on:
      - rabbitmq

  # Tools

  nginx:
    image: ghcr.io/gmrms/nipsr/nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl

  rabbitmq:
    image: rabbitmq:3.10-management
    restart: always
    ports:
      - "15672:15672"
    env_file:
      - env/rabbitmq.env