version: '3.1'

services:

  # Nipsr

  relay:
    image: ghcr.io/gmrms/nipsr/relay:latest
    restart: always
    env_file:
      - env/db.env
      - env/relay.env
      - env/apps.rabbitmq.env
    depends_on:
      - rabbitmq

  processor:
    image: ghcr.io/gmrms/nipsr/processor:latest
    restart: always
    env_file:
      - env/db.env
      - env/processor.env
      - env/apps.rabbitmq.env
    depends_on:
      - rabbitmq

  management:
    image: ghcr.io/gmrms/nipsr/management:latest
    restart: always
    env_file:
      - env/db.env
      - env/management.env

  # Tools

  nginx:
    image: nginx:1.23.3-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "15672:15672"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/public.nipsr.com/fullchain.pem:/etc/nginx/ssl/public.nipsr.com/fullchain.pem
      - /etc/letsencrypt/live/public.nipsr.com/privkey.pem:/etc/nginx/ssl/public.nipsr.com/privkey.pem
      - /etc/letsencrypt/live/nipsr.com/fullchain.pem:/etc/nginx/ssl/nipsr.com/fullchain.pem
      - /etc/letsencrypt/live/nipsr.com/privkey.pem:/etc/nginx/ssl/nipsr.com/privkey.pem

  rabbitmq:
    image: rabbitmq:3.10-management
    restart: always
    env_file:
      - env/rabbitmq.env