name: Build and push Docker images

on:
  release:
    types: [ published ]

jobs:
  build-push:

    env:
      registry: "ghcr.io"
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
      
    - name: Log in to the Container registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ${{ env.registry }}
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: "[Relay] - Extract metadata (tags, labels) for Docker"
      id: relay-metadata
      uses: docker/metadata-action@v4.3.0
      with:
        images: ${{ env.registry }}/${{ github.repository }}/relay

    - name: "[Processor] - Extract metadata (tags, labels) for Docker"
      id: processor-metadata
      uses: docker/metadata-action@v4.3.0
      with:
        images: ${{ env.registry }}/${{ github.repository }}/processor

    - name: "[Management] - Extract metadata (tags, labels) for Docker"
      id: management-metadata
      uses: docker/metadata-action@v4.3.0
      with:
        images: ${{ env.registry }}/${{ github.repository }}/management

    - name: "[Client] - Extract metadata (tags, labels) for Docker"
      id: client-metadata
      uses: docker/metadata-action@v4.3.0
      with:
        images: ${{ env.registry }}/${{ github.repository }}/client

    - name: Build with Maven
      run: |
        cd server
        mvn -B package -Drevision=${{ steps.relay-metadata.outputs.version }}
        cd ..
      
    - name: "[Relay] - Build and push Docker images"
      uses: docker/build-push-action@v4.0.0
      with:
        context: server/relay
        push: true
        file: server/relay/src/main/docker/Dockerfile.jvm
        tags: ${{ steps.relay-metadata.outputs.tags }}
        labels: ${{ steps.relay-metadata.outputs.labels }}
      
    - name: "[Processor] - Build and push Docker images"
      uses: docker/build-push-action@v4.0.0
      with:
        context: server/processor
        push: true
        file: server/processor/src/main/docker/Dockerfile.jvm
        tags: ${{ steps.processor-metadata.outputs.tags }}
        labels: ${{ steps.processor-metadata.outputs.labels }}

    - name: "[Management] - Build and push Docker images"
      uses: docker/build-push-action@v4.0.0
      with:
        context: server/management
        push: true
        file: server/management/src/main/docker/Dockerfile.jvm
        tags: ${{ steps.management-metadata.outputs.tags }}
        labels: ${{ steps.management-metadata.outputs.labels }}

    - name: "[Client] - Build and push Docker images"
      uses: docker/build-push-action@v4.0.0
      with:
        context: client
        push: true
        file: client/docker/Dockerfile.jvm
        tags: ${{ steps.client-metadata.outputs.tags }}
        labels: ${{ steps.client-metadata.outputs.labels }}


