name: Build and push Docker images

on:
  release:
    types: [ published ]

jobs:
  build:

    env:
      registry: "ghcr.io/gmrms/nipsr"
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      
    - name: "[Relay] - Extract metadata (tags, labels) for Docker"
      id: relay-metadata
      uses: docker/metadata-action@v4.3.0
      with:
        images: ${{ env.registry }}/relay
      
    - name: "[Relay] - Build and push Docker images"
      uses: docker/build-push-action@v4.0.0
      with:
        context: relay
        file: src/main/docker/Dockerfile.jvm
        tags: ${{ steps.relay-metadata.outputs.tags }}
        labels: ${{ steps.relay-metadata.outputs.labels }}
      
    - name: "[Processor] - Extract metadata (tags, labels) for Docker"
      id: processor-metadata
      uses: docker/metadata-action@v4.3.0
      with:
        images: ${{ env.registry }}/processor
      
    - name: "[Processor] - Build and push Docker images"
      uses: docker/build-push-action@v4.0.0
      with:
        context: processor
        file: src/main/docker/Dockerfile.jvm
        tags: ${{ steps.processor-metadata.outputs.tags }}
        labels: ${{ steps.processor-metadata.outputs.labels }}


